### ISSUE TITLE
MsSql2008GeographyWriter has issue with internal polygon rings

### ISSUE THREAD

**Issue by wicksell** [NetTopologySuite/NetTopologySuite.IO.SqlServer2008#2]
In MsSql2008GeographyWriter.cs the following line
Array.ForEach(polygon.InteriorRings, ring => AddCoordinates(builder, TryReverseRing((ILinearRing)polygon.ExteriorRing, false).CoordinateSequence));
(in AddPolygon) should be replaced with
Array.ForEach(polygon.InteriorRings, ring => AddCoordinates(builder, TryReverseRing((ILinearRing)ring, false).CoordinateSequence));

**Comment by airbreather** [comment]
Good call, I'll get it fixed.

FYI, I'd recommend using [NetTopologySuite.IO.SqlServerBytes](https://github.com/NetTopologySuite/NetTopologySuite.IO.SqlServerBytes) instead of this for new work where applicable.

**Comment by wicksell** [comment]
OK, thanks for the feedback!
